@GameBoardOnlineApi_HostAddress = http://localhost:5042
@tokenUser1 = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0IiwibmFtZSI6IlZhbGVudGluIn0.IYI28S3SV-EGZ9ZSMWUpqqCJhkjdHK-pq9QmdgEUWiw
@tokenUser2 = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwibmFtZSI6Ikp1bGluZSJ9.svWjRVuHRuJH9V3AhW72PZtF_JtlB0zO8AaBlFM8ogw
@roomId = 1
@gameId = 5

GRAPHQL {{GameBoardOnlineApi_HostAddress}}/graphql

mutation {
    login(name: "Juline", color: "red") {
        id
        token
    }
}

###
GRAPHQL {{GameBoardOnlineApi_HostAddress}}/graphql

mutation {
    login(name: "Valentin", color: "blue") {
        id
        token
    }
}

###

GRAPHQL {{GameBoardOnlineApi_HostAddress}}/graphql
Authorization: Bearer {{tokenUser1}}

query {
    me {
        id
        name
    }
}

###

GRAPHQL {{GameBoardOnlineApi_HostAddress}}/graphql
Authorization: Bearer {{tokenUser1}}

mutation {
    createRoom(name: "Test") {
        id
        users {
            id
            name        
        }
    }
}

###

GRAPHQL {{GameBoardOnlineApi_HostAddress}}/graphql
Authorization: Bearer {{tokenUser2}}

mutation {
    joinRoom(roomId: "{{roomId}}") {
        id
        users {
            id
            name        
        }
    }
}


###

GRAPHQL {{GameBoardOnlineApi_HostAddress}}/graphql
Authorization: Bearer {{tokenUser2}}

query {
    get(gameId: "{{gameId}}") {
        id
        name
        players {
            id
            name        
        }
    }
}

###

GRAPHQL {{GameBoardOnlineApi_HostAddress}}/graphql
Authorization: Bearer {{tokenUser1}}

mutation {
    initializeGame(roomId: "{{roomId}}", gameId: "3a47573c-f1f4-4787-9d62-8c96e29b880b") {
        id
    }
}

###

GRAPHQL {{GameBoardOnlineApi_HostAddress}}/graphql
Authorization: Bearer {{tokenUser1}}

mutation {
    sendChatMessage(roomId: "{{roomId}}", message: "Test") {
        id
    }
}